# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  migrations:
    build:
      context: "/home/wojtek/Git/Project"
      dockerfile: "Project.WebApi/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "service-migrations:dev"
    ports:
    - "127.0.0.1:57000:57000"
    - "127.0.0.1:57200:57200"
    - "127.0.0.1:57400:57400"
    volumes:
    - "/home/wojtek/Git/Project/Project.WebApi:/app:rw"
    - "/home/wojtek/Git/Project:/src:rw"
    - "/home/wojtek/.nuget/packages:/home/app/.nuget/packages"
    - "/home/wojtek/.local/share/JetBrains/RiderRemoteDebugger/2024.3.5/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/usr/share/JetBrains Rider-2024.3.5/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/wojtek/.cache/JetBrains/Rider2024.3/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_6_12_06_55_28:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  project.webapi:
    build:
      context: "/home/wojtek/Git/Project"
      dockerfile: "Project.WebApi/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "projectwebapi:dev"
    ports:
    - "127.0.0.1:57001:57000"
    - "127.0.0.1:57201:57200"
    - "127.0.0.1:57401:57400"
    volumes:
    - "/home/wojtek/Git/Project/Project.WebApi:/app:rw"
    - "/home/wojtek/Git/Project:/src:rw"
    - "/home/wojtek/.nuget/packages:/home/app/.nuget/packages"
    - "/home/wojtek/.local/share/JetBrains/RiderRemoteDebugger/2024.3.5/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/usr/share/JetBrains Rider-2024.3.5/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/wojtek/.cache/JetBrains/Rider2024.3/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_6_12_06_55_28:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
